### ISSUE TITLE
Bug in Multiple Authentication

### ISSUE THREAD

**Issue by TMJEngineers** [adonisjs/adonis-auth#126] opened 2018-09-28 01:56 UTC
Hi,

I have notice that upon logging in on our `admin` auth it also fills in our `user` auth with the same `id` of the logged user. I have tested it on a **fresh adonis setup** to validate my claim. This is what I did and what is the result of it.

**config/auth.js**
<img width="434" alt="screen shot 2018-09-28 at 9 39 39 am" src="https://user-images.githubusercontent.com/29135779/46183376-3a959580-c303-11e8-969b-b63e4f36587a.png">

**Route**
<img width="714" alt="screen shot 2018-09-28 at 9 40 04 am" src="https://user-images.githubusercontent.com/29135779/46183580-200fec00-c304-11e8-8df6-fbf93e0a0046.png">

I only logged the auth of `admin` and console the both authenticator and these were the result.

**Console**
<img width="228" alt="screen shot 2018-09-28 at 9 44 04 am" src="https://user-images.githubusercontent.com/29135779/46183604-37e77000-c304-11e8-958a-9ac9a9d87472.png">
<img width="151" alt="screen shot 2018-09-28 at 9 43 57 am" src="https://user-images.githubusercontent.com/29135779/46183605-3a49ca00-c304-11e8-8484-c199749bcaa2.png">

Please see the `id` in **$attributes**

Did I use the authenticator the right way?

**Comment by thetutlage** [comment] 2018-10-01 08:50
If you look at it closely, this is not a bug.

Your user login with an `id` of `1` let's say. Now you are asking both the authenticators, `admin` and `user` to find a user by querying the database for `id=1`.

If user for `id=1` exists in `users` and also in `admin` table, that means they are logged in.

Also I don't understand the point of creating 2 users table. Ideally `admin` is a different role for the user and creating multiple tables for different roles will not help much

**Comment by TMJEngineers** [comment] 2018-10-02 03:41
hi @thetutlage thank you for your reply, I think I understand the authenticators in a wrong way. I just want to know how do you handle different authentication in different database or table in adonis correctly? or is it supported?  

On our end we separate 2 tables to simplify the process of fetching the 2 type of users and to prevent other dev's specially newly joined dev from making a mistake on fetching users since the access level of each is crucial to the security of the application.

**Comment by RomainLanz** [comment] 2019-08-23 21:57
Closing since issue hasn't been active for a while.
Feel free to create a new one if needed.

**Closed by RomainLanz** 2019-08-23 21:57 UTC
Labels: 🤔 Question
