### ISSUE TITLE
Problem with auth.refreshToken().attempt(email, pwd)

### ISSUE THREAD

**Issue by sitthinutk** [adonisjs/adonis-auth#105] opened 2018-04-01 16:27 UTC
After I register new user with *email, password* to the database. Then I tried to get JWT token right after. With only the following line, It works fine, returning the JWT token.

```
async register ({ auth, request, response }) {
  // register user to database
  try { 
    const token = auth.attempt(email, password) 
    response.send(token)
  } catch (error) {
    console.log(error)
  }
}
```

but when I also need refresh token, so I followed the docs. This one gives error.

```
auth.withRefreshToken().attempt(email, password)
```

here is my JWT auth config in file: _config/auth.js_

```
jwt: {
  serializer: 'lucid',
  model: 'App/Models/User',
  scheme: 'jwt',
  uid: 'email',
  password: 'password',
  options: {
    secret: 'self::app.appKey',
    expiresIn: 86400000, /* 1 day */
    issuer: 'my-auth-provider'
  }
}
```

here is the error I logged

```
TypeError: user.tokens is not a function
    at LucidSerializer.saveToken (/Users/sitthinut/fitgunbackend/node_modules/@adonisjs/auth/src/Serializers/Lucid.js:238:16)
    at JwtScheme._saveRefreshToken (/Users/sitthinut/fitgunbackend/node_modules/@adonisjs/auth/src/Schemes/Jwt.js:116:36)
    at JwtScheme.generate (/Users/sitthinut/fitgunbackend/node_modules/@adonisjs/auth/src/Schemes/Jwt.js:290:56)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I am new to adonis and very happy to give you more information regarding this issue.

**Comment by thetutlage** [comment] 2018-04-01 17:39
Not sure how did you setup the auth, but your `User` model must have a relationship on the `Token` model to store the `refreshToken`

```js
class User extends Model {
  tokens () {
     return this.hasMany('App/Models/Token')
  }
}
```

And ofcourse, their must be a `app/Models/Token.js` model file

**Comment by sitthinutk** [comment] 2018-04-03 01:45
Oh. So the DB models must be something like what we have right after *new project* to make `refreshToken()` works normally?
 
I removed Token table becuz I thought JWT is something stateless which does not need database to help storing it. Can you pls explain?

Thanks in advance

**Comment by thetutlage** [comment] 2018-04-03 04:43
Yes JWT is stateless. However, the refresh tokens needs to be stored in DB, so that we can use it to find a user and then issue to a new token.

**Comment by RomainLanz** [comment] 2018-06-08 19:51
Closing since issue hasn't been active for a while.
Feel free to create a new one if needed.

**Closed by RomainLanz** 2018-06-08 19:51 UTC

**Comment by brenoos** [comment] 2019-04-01 20:32
I'm having the same problem, any solution?

**Comment by RomainLanz** [comment] 2019-04-02 19:44
Please create your own issue and follow provide code to reproduce the issue.
